export class AppConst { 
  // public static SchoolList=['Osem Zaatar Snack Cracker 300G',
  // 'Fairy Lemon 9*1240 Ml',
  // 'Fairy Lemon 16*650Ml',
  // 'Bruschette Martti Mixed Cheese 70G',
  // 'Bruschette Martti Mushrooms &Cream  70G',
  // 'Bruschette Martti Spinach &Cheese 70G',
  // 'Bruschette Martti Tomato Olives &Oreegan',
  // 'Bruschette Martti Pizza 70G',
  // 'Baby Wipes Red',
  // 'Nescafe Classic Jar 200G',
  // 'Baby Wipes Purple',
  // 'Ajax Window Cleaner Blue 750Ml+750Ml',
  // 'Holland Greatest Cheese 0.5K',
  // 'Kelloggs Corn Flakes 750G',
  // 'Safi Sunflower Oil 5L',
  // 'Reema Toilet 32 Roll',
  // 'Always Super Vp 16X18',
  // 'Nutella 600G *6',
  // 'Addyafe Basmati Rice 5K',
  // 'Carton Cups 7Oz',
  // 'Turkish Cup',
  // 'Foul Medammas Canned',
  // 'Pringles Original 18*165Gr',
  // 'Cappy Orange 1.5L',
  // 'Cappy Grape 1.5L',
  // 'Tnuva Amek Cheese',
  // 'Cappy Mango 1.5L',
  // 'Labaneh Dania Plain 400G',
  // 'Salt Salit 1K 1*12',
  // 'Milk Ameed 1L',
  // 'Ariel White Rose 8K',
  // 'Whole Chicken',
  // 'Oreo Classi Bisc 44G 16Psc',
  // 'Reema Kitchen Towel 6 roll',
  // 'Sprite 1.125L',
  // 'Coca Cola 1.125L',
  // 'Puck 24Pcs',
  // 'Zeta Pickled Cucumbes In Brine 7-9',
  // 'Cappy Strawberry & Banana Drink 1.5L',
  // 'Rice Shukha Sunwhite 5K',
  // 'Puck Danish Spread Cheese 500G',
  // 'Al Jebrini Fresh Milk 3% 2L Offer',
  // 'Alaa Al Deen Tissues 800G 2P',
  // 'Kinder Bueno T2*30*4',
  // 'Al Jebrini Long Life Milk 1L',
  // 'Pringles Sour Cream 18*165Gr',
  // 'Shemenit 200G',
  // 'Carefree Plus Large Fresh  48Psc',
  // 'Ariel Color 8K',
  // 'Ulker Pudding Banana 100 Gm',
  // 'Alpella Al Safi 100Gm',
  // 'Ulker Pudding Strawberry 100 G',
  // 'Al Sanabel Wheat Flour 1K',
  // 'Heinz T Paste  12*370G',
  // 'Lipton-Tea 100*1.5G',
  // 'Haifa Flour 1K',
  // 'Alraya Sugar 1K',
  // 'Tuna Marina W/ Oil 170G',
  // 'Roastery 40 Nis',
  // 'Labaneh Dania Plain 900G',
  // 'Bissan Sandwich Bags 19*25Cm',
  // 'Eggs 30 Pcs',
  // 'Safi Corn Oil 5L',
  // 'Alquds Mortadella  1K',
  // 'Abu Eta Noodles 200G',
  // 'Holland 0.5K Greatest Cheese',
  // 'Aljunaidi Milk Fresh Offer*2L',
  // 'Jericho Water 8*1.5L Case',
  // 'Haifa Wheat Smeed 1K',
  // 'Harpic Toilet Cleaner Hygiene 750Ml',
  // 'Harpic Toilet Cleaner Citrus Force 750Ml',
  // 'Harpic Original Limescale Remover Blue',
  // 'Fanta Orange 1.125L',
  // 'Fanta Fruity Flavoured 1.125Ml',
  // 'Bugles Natcho Cheese 40G',
  // 'Mr.Chips Bugles Orignal 40G',
  // 'Bugles Chili Cheese 40G',
  // 'Sin. Al Quds Mort P.O.P',
  // 'Bread Sarfande Kmaj',
  // 'Roast Beef',
  // 'Xl Regular 250Ml',
  // 'Bounty 57G',
  // 'Snickers 50G',
  // 'Kinder Bueno White T2*30*4',
  // 'Mars 51G',
  // 'Twix 50G',
  // 'Alma Classic Chocolate 200G',
  // 'Doritos Grell Chips 185 G',
  // 'Doritos With Lemon Hot 200G',
  // 'Osem Bisle With Grill Flavor 50 G',
  // 'Osem Bisle With Bpq Flavor 50 G',
  // 'Pepsi Plastic 250Ml',
  // 'Seven Up  Plastic 250Ml',
  // 'Rice Shukha Sunwhite 10K',
  // 'Al Kasih Tomato Paste 135G',
  // 'Tuna Marina 95G',
  // 'Tuna Marina Light Solid/Piri Piri 95G',
  // 'Reema Toilet Paper Reemix 18Rolls',
  // 'Dove Soap Bars White 4*100G',
  // 'Ariel Lq Ms 4X2.47L/38Sc-Jup-Isr',
  // 'Pringles Salt & Vinegar 165Gm',
  // 'Pringles Ketchup 18*165Gr',
  // 'Mixed Salad 125G',
  // 'Al Junaidi Corn Salad 125G',
  // 'Kinder Joy Girl T1X16X9 Collection',
  // 'Kinder Joy  Boy T1X16X9 Collection',
  // 'Filiz Farfalle 400G',
  // 'Filiz Fusilli 400G',
  // 'Filiz Penne Rigate 400G',
  // 'Filiz Pipo Rigate 400G',
  // 'Filiz Shell 400G',
  // 'Filiz Farballe Tonde 400G',
  // 'Filiz Spaghettini 400G',
  // 'Reema750*2',
  // 'Bags Food 25*35 Cm',
  // 'Baby Wipes Tango',
  // 'Pringles Hot & Spicy 18*165Gr',
  // 'Ali Baba Box 24Psc',
  // 'M&M S Peanut 45G',
  // 'M&Ms Chocolate 45G',
  // 'Maltesers 37G',
  // 'Puck Topping 170G',
  // 'Pringles Barbecue 18*165Gr',
  // 'Pringles Cheddar Cheese 19*165 Gr',
  // 'Always Ultra Vp Long 6X24',
  // 'Always Ultra Vp Night 8X20',
  // 'Pepsi 1L',
  // 'Pepsi Maxi Free Suger 1L',
  // 'Seven Up 1L',
  // 'Mirinda 1L',
  // 'Bilady Kids Milk W Strawberry 200Ml',
  // 'Bilady Kids Milk W Choclate 200Ml',
  // 'Xl Energy Drink Mixer Mojito 250Ml',
  // 'Siginal Toothpaste Apples 125Ml',
  // 'Siginal Herbal Toothpaste 125Ml',
  // 'Eti Petit Beurre Biscute 1000G',
  // 'Al Zahra Strawberry Jelly 85G',
  // 'Americana Sweet Corn 400G',
  // 'Margarine Butter  200G',
  // 'Al Zahra Vanilla Can 100G',
  // 'Al Zahra Baking Powder Can 100G',
  // 'Halibona Hevey Cream 170G',
  // 'Al Zahra Instant Cream White',
  // 'Al Zahra Cream Carammel 70G',
  // 'Halk Petibor Biscuits 900Gm',
  // 'Fine Fluffy 10 P Tissuse',
  // 'Roastery 60 Nis',
  // 'Roastery 36 Nis',
  // 'Roastery 48 Nis',
  // 'Roastery 32 Nis',
  // 'Roastery 56',
  // 'Roastery 20 Nis',
  // 'Siniora Smoked Beef Sausages 1K',
  // 'Al Rabie Milk Str 200Ml',
  // 'Al Rabie Milk Chioclate 200Ml',
  // 'Al Rabie Milk Banana 200Ml',
  // 'Siginal Toothpaste Cavity Fighter 125Ml',
  // 'Roastery 44 Nis',
  // 'Roastery 30 Nis',
  // 'Galaxy Smoth Cream Milk 40G',
  // 'Galaxy Smooth Dark Choclate 40G',
  // 'White Sugar 10K',
  // 'Fairy Orginal 16*650Ml',
  // 'Fairy Original 9*1240 M',
  // 'Americana Sardines Hot 120G',
  // 'Fatafeat Tuna Chunks Hot Chili 140G',
  // 'Almarai Cheddar 500 Gm',
  // 'Cappy Lemon Mint Drink 1.5 L',
  // 'Cappy Red Cherry  1.5L',
  // 'Pinar Choclate Yogurt 110Ml',
  // 'Pinar Strawberry Yogurt 110 Ml',
  // 'Chicken Boneless Breast',
  // 'Whole Chicken Aziza',
  // 'Cheetos Crunchy Cheese 30G',
  // 'Chetos Catchup 15G',
  // 'Chetos Xo 17G',
  // 'Marina Light Tuna Piri Piri Veg.Oil160Gm',
  // 'S.K  Whole Lentils 1Kg',
  // 'S.K Chickpeas 1K',
  // 'S.K Corn 1K',
  // 'S.K Red Lenrils 1K',
  // 'Jibrini Chocolate Pudding 1Psc',
  // 'Jibrini Vanilla Pudding 1Psc',
  // 'Tapuzina Grape 1.5L',
  // 'Tapuzina Apple 1.5 Litter',
  // 'Trash Bags Gold Ligature 60 Bags',
  // 'Coffee Mate 400Gm',
  // 'Always Ultra Vp Normal 12X28',
  // 'Royal Pea & Carrot Frozen 400Gm',
  // 'Royal Corn Frozen 400Gm',
  // 'Homos Extra 250G',
  // 'Tapuzina Orange 1.5L',
  // 'Milk Puck 0.3%',
  // 'Puck Milk 3.5% 1 L',
  // 'Siniora Luncheon Meat 800 Gr',
  // 'Salt Salit 12K',
  // 'Nestle Pure Life 12*500M Case',
  // 'Nestle Pure Life 6*1.5L Case',
  // 'Italpasta #77 500G',
  // 'Italpasta #82 500G',
  // 'Shemenit 15% 250G Labeshol',
  // 'Barilla La Collezione Fettuccine 500G',
  // 'Rice Shukha Sunwhite 2K',
  // 'Abu Aita Pasta -01 350G',
  // 'Abu Aita Pasta -00 350G',
  // 'Shemenit 15% 500G Labeshol',
  // 'Tea Carton Cups 9Oz',
  // 'Heinz Plastic Tk 10X700G',
  // 'Indomie Special Chicken Curry 80G1*5',
  // 'Indomie Vegetable Flav 80G1*5',
  // 'Indomie Special Chicken Flav 80G1*5',
  // 'Roastery 80 Nis',
  // 'Italpasta #88 500G',
  // 'Comfort Blue 3L',
  // 'Sprite 330Ml',
  // 'Coca Cola 330Ml',
  // 'Lays Grill Potato Chips 35G',
  // 'Doritos W/Grill 45G',
  // 'Lays Maxican Potato Chips 35G',
  // 'Tabochips Lays 40G',
  // 'Prigat Lemon Mint 1.5L',
  // 'Prigat Orange 1.5L',
  // 'Prigat Grapes 1.5L',
  // 'Prigat Apple 1.5L',
  // 'Mixed Salad  200G',
  // 'Tapuzina Srwaberry Banana  1.5L',
  // 'Cloth Tables 25 M',
  // 'Hand Soap Rose 500 Ml',
  // 'Hand Soap Peach 500 Ml',
  // 'Hand Soap Apple 500 Ml',
  // 'Crackerbegala 400G 8 Shape',
  // 'Crackerbegala Salty  Figners 375G',
  // 'Al Khayyal Sunflower Oil 3L',
  // 'Maadan Carlo Export 125 gm',
  // 'Maadan Vanil Export 125G',
  // 'Sun Top Orange 125Ml',
  // 'Sun Top Cola 125Ml',
  // 'Sun Top Berries 125Ml',
  // 'Fatafeat Tuna Chunks In Vegetableoil140G',
  // 'Siniora Luncheon Turky 800 Gr',
  // 'Lazeza Tahina 900G',
  // 'Puck Regular Slices 170G',
  // 'Puck Cheddar Slices 170G',
  // 'Bavaria Apple Can 330Ml',
  // 'Bavaria Pomegranate Can 330L',
  // 'Bavaria Peach Can 330Ml',
  // 'Bavaria Strawberry Can 330Ml',
  // 'El Maleka Spaghettini  400G',
  // 'El Maleka Fusilli 400G',
  // 'El Maleka Penne 400G',
  // 'Royal Pea Frozen 400Gm',
  // 'Royal Soup  Frozen 400Gm',
  // 'Cappy Pear Kiwi & Cactus1.5L',
  // 'Dettol Soap Anti Bacterial Active 125G',
  // 'Dettol Soap Fresh 125G',
  // 'Dettol Soap  Anti-Bacterial Cool 125G',
  // 'Ghazal Ghee 1K',
  // 'Mr.Brown Cappuccino Iced Coffe 240G',
  // 'Mr.Brown Vanilla  Iced Coffe 240Ml',
  // 'Mr Brown Iced Coffee 240Ml',
  // 'Nutella 750 G*12',
  // 'Halawa Al Helal Fingers Choco  70G',
  // 'Halawa Al Hilal Fingers Vanilla 70G',
  // 'Packed Chicken Drumstick',
  // 'Khasawi',
  // 'Italpasta #57 500G',
  // 'Cappy Grapefruit 1.5 L',
  // 'Roastery 24 Nis',
  // 'Cheetos Dolfen Corn Cheese 15G',
  // 'Roastery 28 Nis',
  // 'Roastery 16 Nis',
  // 'Roastery 7Nis',
  // 'Hand Soap Aolevera 500 Ml',
  // 'Barilla Lasagne 500G',
  // 'Aiden Green Olive W/O Seeds 560G',
  // 'Black Olives Rings 560G',
  // 'Doritos W Pepper 45G',
  // 'El Maleka Elbow 400G',
  // 'Heinz T Paste  48*135G',
  // 'Orbit Spearmint Pellets',
  // 'Orbit Blueberry Pellets 14G',
  // 'Maggi Soup 11Vegetable 53G',
  // 'Maggi Soup Chicken Noodle60G',
  // 'Maggi Soup Spring Season 59G',
  // 'Maggi Cream Of Mashroom Soup 68G',
  // 'Peas& Carrots Alsalam 400Gm',
  // 'Lazeza Whole Sweet Corn 340G',
  // 'Willi Food Sweetened Condensed Milk 397G',
  // 'Schweppes Apple Drink 1.125L',
  // 'Schweppes Grape Drink 1.125L',
  // 'Schweppes Strwberry Drink 1.125L',
  // 'Bavaria Original Beer Can 330Ml',
  // 'Filiz Elbow 400G',
  // 'Elldei Hazelnut Bis 45G',
  // 'Elldei Hazelnut Bis Cocoa Flavor45G',
  // 'Vitrac Strawberry Jam 900G',
  // 'Harpic Toilet Cleaner Spring Power 750Ml',
  // 'Mr Chips Pizza Chips 30G',
  // 'Mr Chips Crocodilechips 30G',
  // 'Filiz Macaroni 400G',
  // 'Mr Chips Disco Chips 30G',
  // 'Mr Chips French Cheese 85G',
  // 'Mr Chips Paprika85G',
  // 'Zadona Cucumber In Salt 7-9 540G',
  // 'Sk Granulated Garlic100G',
  // 'S.K Granulated Onion 125G',
  // 'Al-Salam Potato 2.5Kg',
  // 'Pringles Original 12*40Gr',
  // 'Pringles Sour Cream  12*40Gr',
  // 'Lays Salted Potato Chips 18G',
  // 'Tapu Chips 18G',
  // 'Mixed Vege. Alsalam 400Gm',
  // 'Indomie Special Chicken Flavor 80G',
  // 'Indomie Noodles Vegetable 80G',
  // 'Sprite  150 Ml',
  // 'Coca Cola 150 Ml',
  // 'Al-Salam Frozen Sweet Corn 800G',
  // 'Al Salam Peas & Carots Frozen Soup 800G',
  // 'Fanta Orange150 Ml',
  // 'Aquafresh Fresh & Minty Tube 100Ml X1',
  // 'Aquafresh Mild & Minty Tube 100Ml X1',
  // 'Seven Up Sugar Free 1L',
  // 'Orbit Peppermint Pellets',
  // 'Cappy Apple Drink 1.5L',
  // 'Al Zahra Instant Ceamy Chocolate',
  // 'Pepsi 1.5L',
  // 'Seven Up 1.5L',
  // 'Jibrini Strawberry Bilady Yogurt',
  // 'Moletal Corn 800G',
  // 'Moletal Frozen Peas 800G',
  // 'Reeses Nut Bar Chocolate 47G',
  // 'Hersheys Reeses 3 Cups 51G',
  // 'Johnsons Baby Shampoo 750ml',
  // 'Tora Bika Cappuccion 500G Box 3',
  // 'Al-Rajeh Dw Liquid 4L',
  // 'Cllour Galon 4 Ltr',
  // 'Pringles Hot & Spicy 12*40Gr',
  // 'Mirinda 1.5L',
  // 'Farm Frites Green Frozen Molokiah 400G',
  // 'Frozen Okra Extra Farm Frites 400G',
  // 'Star Sugar 10K',
  // 'Awafi Rice 25K',
  // 'Saleh Khalaf White Beans 1Kg',
  // 'Ketchup 750G Normal 15961',
  // 'Frozen Corn 800G',
  // 'Frozen Peas 800G',
  // 'Al Juneidi Fruiti Apple Nectar 200Ml',
  // 'Al Juniedi Fruiti Mango Nectar 200Ml',
  // 'Hand Soap Oat 500 Ml',
  // 'Al Zahra Cacao 100G',
  // 'Orbit Eucalyptus 10 Pellets  Without Sug',
  // 'Filiz Spaghetti 400G',
  // 'Indomie Chicken Flavour 60G',
  // 'Indomie Curry Flavour 60G',
  // 'Alma Classic Lemon 200G',
  // 'Sun Top Mango 125Ml',
  // 'Sun Top Fruits 125Ml',
  // 'Sun Top Apple 125Ml',
  // 'Axe Deo For Men Black 150Ml',
  // 'Axe Deo For Men Black Night 150Ml',
  // 'Fresco Chocolate Milk 200Ml',
  // 'Choco Milk Aljunedidi 200Ml',
  // 'Schweppes Exotic Drink 1.125L',
  // 'Galaxy Flutes 11.25G*24',
  // 'Bruschette Martti Sweet Chili 70G',
  // 'Bruschette Mixd Vegetables 70G',
  // 'Rice Shukha Sunwhite 25K',
  // 'Alma Balgian Chocolate 200G',
  // 'Mirinda Plastic 250Ml',
  // 'Cadbury Twirl 43G',
  // 'Cadbury Snack Sandwich 26G',
  // 'Schweppes Orange Drink 1.125L',
  // 'Roastery 72 Nis',
  // 'Galaxy Fruit & Nut 40G',
  // 'Galaxy White Chocolate38G',
  // 'Galaxy Hazelnut 36G',
  // 'Al Dyafa Tuna Hot 80G',
  // 'Al Dyafa Tuna 80G',
  // 'Prigat Mango 1.5L',
  // 'Baby Wipes 72',
  // 'Fresher Strawberry Drinl 250Ml',
  // 'Fresher Watermelon&Strawberry   Drinl 25',
  // 'Fresa Fresher Lemon Mint 250Ml',
  // 'Fresher Lemon  Drinl 250Ml',
  // 'Fresher Pomegranate Drinl 250Ml',
  // 'Abu Aita Pasta -02 350G',
  // 'Tapuzina Manga 1.5L',
  // 'S.K Sweat Lupines 1K',
  // 'Shawer Tahina 1K',
  // 'Al Juniedi Juice Up Grape 200Ml',
  // 'Bisc.300G Choco Argeliot',
  // 'Bisc.300G Argeliot Strawberry 9297',
  // 'Foul Harvest Chilli 380G',
  // 'Foul Harvest Modams 380G',
  // 'Coca Cola Plastic 250Ml',
  // 'Sprite 250Ml',
  // 'Roastery Unit 8 Nis',
  // 'Bisc.300G Argeliot Raspberry',
  // 'Laban W/Fruit 150G',
  // 'Caramel Vanilla 135G',
  // 'Caramel Choco 135G',
  // 'Star Sugar 1K',
  // 'Roastery 130 Nis',
  // 'Turkey Innards',
  // 'Al Salam Mix Vegetable Frozen Soup 800G',
  // 'Pinar Banana Yogurt 110 Ml',
  // 'Alma Belgian Lemon 200G',
  // 'Corn Salad 200G',
  // 'Al Zahra Orange Jelly 85G',
  // 'Al Zahra Berry Jelly 85G',
  // 'Al Zahra Lemon Jelly 85G',
  // 'Tat Lentils Crushed 1K',
  // 'Pinar Vanilla Yogurt 110Ml',
  // 'Mr Chips Salt 85G',
  // 'Aljuneidi Turkish 200Gm',
  // 'Al Khasab Rice10K',
  // 'Schweppes Mango Drink 1.125L',
  // 'Bugles Natcho Cheese 75G',
  // 'Bugles Chilli Cheese 75G',
  // 'Italpasta #103 500G',
  // 'Sk-Chicken Spice 100G',
  // 'Sk-Mixed Spices 100G',
  // 'Signal Toothpaste 25Ml',
  // 'Al Juniedi Juice Up Orange 200Ml',
  // 'Tapuzina Grapefruit 1.5L',
  // 'Sweet Corn Alsalam 400Gm',
  // 'Boneless Lamp',
  // 'Schweppes Lemon Drink 1.125L',
  // 'Indomie Vegetable Flavour 60G',
  // 'Seven Up 500Ml',
  // 'Pepsi 500Ml',
  // 'Mr.Chips Bugles Orignal 75G',
  // 'Schweppes Pink Lemonade Drink 1.125L',
  // 'Filiz Sedanin 400G',
  // 'Osem Craker Begala Circle 400G',
  // 'Lazeza  Pinapple Slices 850G',
  // 'Fanta Apple 1.125 L',
  // 'Wc Masteer Bath Stone Lemon',
  // 'Wc Masteer Bath Stone Flower',
  // 'Galaxy Crispy 36G',
  // 'Jamjom Baladi Cheese Regular',
  // 'Jamjom Plain Labaneh',
  // 'Corn Grain 1K',
  // 'Ajjawi Lentils Crushed 1K',
  // 'Fanta Strawberry 1.125L',
  // 'Prigat Grapefruit 1.5L',
  // 'Danette Cookies 75Gm',
  // 'Danette Vanila 75Gm',
  // 'Danette Cream Cramel 80Gm',
  // 'Danette Cocolate75Gm',
  // 'Danette Cotton Candy75Gm',
  // 'Plate Colore S-Size 170Mm',
  // 'Plate Color B-Size 220Mm',
  // 'Prigat Strawbary Banana 1.5L',
  // 'Pringles Cheesy Cheese 165Gr',
  // 'Pringles Paprika 165G',
  // 'Candia Choclat Milk 200Gm',
  // 'Candia Straw. Milk 200Gm',
  // 'Al Junaidi Fruity Gauava 1 L',
  // 'Al Junaidi Fruity Mango 1 L',
  // 'Al Junaidi Fruity Apple 1 L',
  // 'Al Junaidi Fruity Pineapple 1 L',
  // 'Bavaria Mango Passion Can 330Ml']
  
  public static RamadanList=['Kinder Joy Girl T1X16X9 Collection',
  'Baby Wipes Purple',
  'Baby Wipes Red',
  'Kinder Joy  Boy T1X16X9 Collection',
  'Nutella 600G *6',
  'Kinder Bueno T2*30*4',
  'Americana Sweet Corn 400G',
  'Osem Zaatar Snack Cracker 300G',
  'Bruschette Martti Mixed Cheese 70G',
  'Bruschette Martti Mushrooms &Cream  70G',
  'Bruschette Martti Spinach &Cheese 70G',
  'Bruschette Martti Tomato Olives &Oreegan',
  'Bruschette Martti Pizza 70G',
  'Foul Medammas Canned',
  'Nescafe Classic Jar 200G',
  'Lipton-Tea 100*1.5G',
  'Coffee Mate 400Gm',
  'Salt Salit 1K 1*12',
  'Alraya Sugar 1K',
  'Cappy Orange 1.5L',
  'Cappy Grape 1.5L',
  'Coca Cola 1.125L',
  'Al Jebrini Long Life Milk 1L',
  'Safi Sunflower Oil 5L',
  'Holland Greatest Cheese 0.5K',
  'Tnuva Amek Cheese',
  'Sprite 1.125L',
  'Jericho Water 8*1.5L Case',
  'Bread Sarfande Kmaj',
  'Haifa Flour 1K',
  'Labaneh Dania Plain 400G',
  'Rice Shukha Sunwhite 5K',
  'Maadan Carlo Export 125 gm',
  'Maadan Vanil Export 125G',
  '7 Days Cocoa Mini Roll With Vanilla 8Pcs',
  '7Days Croissant Cocoa 240G',
  'Heinz T Paste  12*370G',
  'Al Zahra Strawberry Jelly 85G',
  'Carefree Plus Large Fresh  48Psc',
  'Doritos Grell Chips 185 G',
  'Doritos With Lemon Hot 200G',
  'Italpasta #88 500G',
  'Italpasta #82 500G',
  'Al Jebrini Fresh Milk 3% 2L Offer',
  'Milk Ameed 1L',
  'Kelloggs Corn Flakes 750G',
  'Reema Toilet 32 Roll',
  'Pepsi 1L',
  'Seven Up 1L',
  'Royal Pea & Carrot Frozen 400Gm',
  'Hand Soap Rose 500 Ml',
  'Hand Soap Apple 500 Ml',
  'Hand Soap Peach 500 Ml',
  'Royal Pea Frozen 400Gm',
  'Royal Corn Frozen 400Gm',
  'Mixed Vege. Alsalam 400Gm',
  'Peas& Carrots Alsalam 400Gm',
  'Sun Top Orange 125Ml',
  'Sun Top Berries 125Ml',
  'Royal Soup  Frozen 400Gm',
  'Sun Top Fruits 125Ml',
  'Sun Top Mango 125Ml',
  'Seven Up Sugar Free 1L',
  'Mirinda 1L',
  'Pepsi Maxi Free Suger 1L',
  'Nestle Nesquik Breakfast Cereal 375G',
  'Lays Grill Potato Chips 35G',
  'Doritos W/Grill 45G',
  'Puck Danish Spread Cheese 500G',
  'Always Super Vp 16X18',
  'Turkish Cup',
  'Pringles Original 18*165Gr',
  'Danette Cotton Candy75Gm',
  'Pringles Cheesy Cheese 165Gr',
  'Pringles Paprika 165G',
  'Candia Choclat Milk 200Gm',
  'Candia Straw. Milk 200Gm',
  'Al Junaidi Fruity Gauava 1 L',
  'Al Junaidi Fruity Mango 1 L',
  'Al Junaidi Fruity Apple 1 L',
  'Al Junaidi Fruity Pineapple 1 L']
  
  public static SchoolList=['Osem Zaatar Snack Cracker 300G',
  'Bruschette Martti Tomato Olives &Oreegan',
  'Bruschette Martti Pizza 70G',
  'Baby Wipes Red',
  'Nescafe Classic Jar 200G',
  'Baby Wipes Purple',
  'Ajax Window Cleaner Blue 750Ml+750Ml',
  'Holland Greatest Cheese 0.5K',
  'Kelloggs Corn Flakes 750G',
  'Safi Sunflower Oil 5L',
  'Reema Toilet 32 Roll',
  'Always Super Vp 16X18',
  'Nutella 600G *6',
  'Addyafe Basmati Rice 5K',
  'Carton Cups 7Oz',
  'Turkish Cup',
  'Foul Medammas Canned',
  'Pringles Original 18*165Gr',
  'Cappy Orange 1.5L',
  'Cappy Grape 1.5L',
  'Puck 24Pcs',
  'Zeta Pickled Cucumbes In Brine 7-9',
  'Cappy Strawberry & Banana Drink 1.5L',
  'Rice Shukha Sunwhite 5K',
  'Puck Danish Spread Cheese 500G',
  'Al Jebrini Fresh Milk 3% 2L Offer',
  'Alaa Al Deen Tissues 800G 2P',
  'Kinder Bueno T2*30*4',
  'Al Jebrini Long Life Milk 1L',
  'Pringles Sour Cream 18*165Gr',
  'Shemenit 200G',
  'Carefree Plus Large Fresh  48Psc',
  'Alraya Sugar 1K',
  'Tuna Marina W/ Oil 170G',
  'Roastery 40 Nis',
  'Labaneh Dania Plain 900G',
  'Bissan Sandwich Bags 19*25Cm',
  'Eggs 30 Pcs',
  'Safi Corn Oil 5L',
  'Alquds Mortadella  1K',
  'Abu Eta Noodles 200G',
  'Holland 0.5K Greatest Cheese',
  'Fanta Fruity Flavoured 1.125Ml',
  'Bugles Natcho Cheese 40G',
  'Mr.Chips Bugles Orignal 40G',
  'Bugles Chili Cheese 40G',
  'Sin. Al Quds Mort P.O.P',
  'Bread Sarfande Kmaj',
  'Roast Beef',
  'Xl Regular 250Ml',
  'Doritos With Lemon Hot 200G',
  'Osem Bisle With Grill Flavor 50 G',
  'Bags Food 25*35 Cm',
  'Baby Wipes Tango',
  'Pringles Hot & Spicy 18*165Gr',
  'Ali Baba Box 24Psc',
  'M&M S Peanut 45G',
  'M&Ms Chocolate 45G',
  'Maltesers 37G',
  'Puck Topping 170G',
  'Pringles Barbecue 18*165Gr',
  'Pringles Cheddar Cheese 19*165 Gr',
  'Always Ultra Vp Long 6X24',
  'Always Ultra Vp Night 8X20',
  'Pepsi 1L',
  'Pepsi Maxi Free Suger 1L',
  'Seven Up 1L',
  'Al Zahra Strawberry Jelly 85G',
  'Americana Sweet Corn 400G',
  'Margarine Butter  200G',
  'Al Zahra Vanilla Can 100G',
  'Al Zahra Baking Powder Can 100G',
  'Halibona Hevey Cream 170G',
  'Al Zahra Instant Cream White',
  'Al Rabie Milk Str 200Ml',
  'Al Rabie Milk Chioclate 200Ml',
  'Al Rabie Milk Banana 200Ml',
  'Siginal Toothpaste Cavity Fighter 125Ml',
  'Roastery 44 Nis',
  'Roastery 30 Nis',
  'Galaxy Smoth Cream Milk 40G',
  'Galaxy Smooth Dark Choclate 40G',
  'White Sugar 10K',
  'Fairy Orginal 16*650Ml',
  'Fairy Original 9*1240 M',
  'Whole Chicken Aziza',
  'Cheetos Crunchy Cheese 30G',
  'Chetos Catchup 15G',
  'Chetos Xo 17G',
  'Marina Light Tuna Piri Piri Veg.Oil160Gm',
  'S.K  Whole Lentils 1Kg',
  'S.K Chickpeas 1K',
  'S.K Corn 1K',
  'S.K Red Lenrils 1K',
  'Jibrini Chocolate Pudding 1Psc',
  'Jibrini Vanilla Pudding 1Psc',
  'Tapuzina Grape 1.5L',
  'Tapuzina Apple 1.5 Litter',
  'Trash Bags Gold Ligature 60 Bags',
  'Coffee Mate 400Gm',
  'Always Ultra Vp Normal 12X28',
  'Abu Aita Pasta -00 350G',
  'Shemenit 15% 500G Labeshol',
  'Tea Carton Cups 9Oz',
  'Heinz Plastic Tk 10X700G',
  'Indomie Special Chicken Curry 80G1*5',
  'Indomie Vegetable Flav 80G1*5',
  'Indomie Special Chicken Flav 80G1*5',
  'Roastery 80 Nis',
  'Italpasta #88 500G',
  'Comfort Blue 3L',
  'Sprite 330Ml',
  'Coca Cola 330Ml',
  'Lays Grill Potato Chips 35G',
  'Doritos W/Grill 45G',
  'Lays Maxican Potato Chips 35G',
  'Tabochips Lays 40G',
  'Prigat Lemon Mint 1.5L',
  'Siniora Luncheon Turky 800 Gr',
  'Lazeza Tahina 900G',
  'Puck Regular Slices 170G',
  'Puck Cheddar Slices 170G',
  'Bavaria Apple Can 330Ml',
  'Bavaria Pomegranate Can 330L',
  'Bavaria Peach Can 330Ml',
  'Bavaria Strawberry Can 330Ml',
  'El Maleka Spaghettini  400G',
  'El Maleka Fusilli 400G',
  'El Maleka Penne 400G',
  'Royal Pea Frozen 400Gm',
  'Mr Brown Iced Coffee 240Ml',
  'Nutella 750 G*12',
  'Halawa Al Helal Fingers Choco  70G',
  'Halawa Al Hilal Fingers Vanilla 70G',
  'Packed Chicken Drumstick',
  'Khasawi',
  'Hand Soap Aolevera 500 Ml',
  'Barilla Lasagne 500G',
  'Aiden Green Olive W/O Seeds 560G',
  'Orbit Blueberry Pellets 14G',
  'Maggi Soup 11Vegetable 53G',
  'Maggi Soup Chicken Noodle60G',
  'Maggi Soup Spring Season 59G',
  'Maggi Cream Of Mashroom Soup 68G',
  'Peas& Carrots Alsalam 400Gm',
  'Lazeza Whole Sweet Corn 340G',
  'Willi Food Sweetened Condensed Milk 397G',
  'Schweppes Apple Drink 1.125L',
  'Schweppes Grape Drink 1.125L',
  'Schweppes Strwberry Drink 1.125L',
  'Bavaria Original Beer Can 330Ml',
  'Filiz Elbow 400G',
  'Elldei Hazelnut Bis 45G',
  'Elldei Hazelnut Bis Cocoa Flavor45G',
  'Vitrac Strawberry Jam 900G',
  'Harpic Toilet Cleaner Spring Power 750Ml',
  'Mr Chips Pizza Chips 30G',
  'Mr Chips Crocodilechips 30G',
  'Filiz Macaroni 400G',
  'Mr Chips Disco Chips 30G',
  'Mr Chips French Cheese 85G',
  'Mr Chips Paprika85G',
  'Zadona Cucumber In Salt 7-9 540G',
  'Sk Granulated Garlic100G',
  'S.K Granulated Onion 125G',
  'Al-Salam Potato 2.5Kg',
  'Pringles Original 12*40Gr',
  'Pringles Sour Cream  12*40Gr',
  'Lays Salted Potato Chips 18G',
  'Tapu Chips 18G',
  'Mixed Vege. Alsalam 400Gm',
  'Indomie Special Chicken Flavor 80G',
  'Indomie Noodles Vegetable 80G',
  'Sprite  150 Ml',
  'Coca Cola 150 Ml',
  'Al-Salam Frozen Sweet Corn 800G',
  'Al Salam Peas & Carots Frozen Soup 800G',
  'Fanta Orange150 Ml',
  'Aquafresh Fresh & Minty Tube 100Ml X1',
  'Aquafresh Mild & Minty Tube 100Ml X1',
  'Seven Up Sugar Free 1L',
  'Orbit Peppermint Pellets',
  'Cappy Apple Drink 1.5L',
  'Al Zahra Instant Ceamy Chocolate',
  'Pepsi 1.5L',
  'Seven Up 1.5L',
  'Jibrini Strawberry Bilady Yogurt',
  'Moletal Corn 800G',
  'Moletal Frozen Peas 800G',
  'Reeses Nut Bar Chocolate 47G',
  'Hersheys Reeses 3 Cups 51G',
  'Johnsons Baby Shampoo 750ml',
  'Tora Bika Cappuccion 500G Box 3',
  'Al-Rajeh Dw Liquid 4L',
  'Cllour Galon 4 Ltr',
  'Pringles Hot & Spicy 12*40Gr',
  'Mirinda 1.5L',
  'Farm Frites Green Frozen Molokiah 400G',
  'Frozen Okra Extra Farm Frites 400G',
  'Star Sugar 10K',
  'Awafi Rice 25K',
  'Saleh Khalaf White Beans 1Kg',
  'Ketchup 750G Normal 15961',
  'Frozen Corn 800G',
  'Frozen Peas 800G',
  'Al Juneidi Fruiti Apple Nectar 200Ml',
  'Al Juniedi Fruiti Mango Nectar 200Ml',
  'Hand Soap Oat 500 Ml',
  'Al Zahra Cacao 100G',
  'Orbit Eucalyptus 10 Pellets  Without Sug',
  'Filiz Spaghetti 400G',
  'Indomie Chicken Flavour 60G',
  'Indomie Curry Flavour 60G',
  'Alma Classic Lemon 200G',
  'Sun Top Mango 125Ml',
  'Sun Top Fruits 125Ml',
  'Sun Top Apple 125Ml',
  'Axe Deo For Men Black 150Ml',
  'Axe Deo For Men Black Night 150Ml',
  'Fresco Chocolate Milk 200Ml',
  'Choco Milk Aljunedidi 200Ml',
  'Galaxy Fruit & Nut 40G',
  'Galaxy White Chocolate38G',
  'Galaxy Hazelnut 36G',
  'Fresher Watermelon&Strawberry   Drinl 25',
  'Fresa Fresher Lemon Mint 250Ml',
  'Fresher Lemon  Drinl 250Ml',
  'Fresher Pomegranate Drinl 250Ml',
  'Abu Aita Pasta -02 350G',
  'Tapuzina Manga 1.5L',
  'S.K Sweat Lupines 1K',
  'Laban W/Fruit 150G',
  'Caramel Vanilla 135G',
  'Caramel Choco 135G',
  'Turkey Innards',
  'Al Salam Mix Vegetable Frozen Soup 800G',
  'Pinar Banana Yogurt 110 Ml',
  'Alma Belgian Lemon 200G',
  'Corn Salad 200G',
  'Al Zahra Orange Jelly 85G',
  'Al Zahra Berry Jelly 85G',
  'Al Zahra Lemon Jelly 85G',
  'Bugles Chilli Cheese 75G',
  'Italpasta #103 500G',
  'Sk-Chicken Spice 100G',
  'Sk-Mixed Spices 100G',
  'Signal Toothpaste 25Ml',
];
  public static ItemLists={SchoolList:AppConst.SchoolList,RamadanList:AppConst.RamadanList}

  public static RecommendationItems =
  [{'ItemName': 'Tnuva Amek Cheese                       ',
'RecItems': ['Siniora Turkey Breast Pabrika           ',
 'Siniora Bbq                             ',
 'Mays Hodlavan Turkey Breast             ',
 'Oaf Tof Breast And Basterma             ',
 'Salami Oaf Tof                          ',
 'Sin Roast Beef Plain                    ']},
{'ItemName': 'Produce 9 Nis                           ',
'RecItems': ['Produce 10 Nis                          ',
 'Produce 12 Nis                          ',
 'Produce 8 Nis                           ',
 'Produce 5 Nis                           ',
 'Produce 8 Nis                           ',
 'Produce 7 Nis                           ']},
{'ItemName': 'Baby Wipes Red                          ',
'RecItems': ['Baby Wipes Purple                       ',
 'Baby Wipes Tango                        ',
 'Baby Wipes Tango                        ']},
{'ItemName': 'Twix 50G                                ',
'RecItems': ['Snickers 50G                            ',
 'Bounty 57G                              ',
 'Bounty 57G                              ',
 'Mars 51G                                ',
 'Mars 51G                                ',
 'Mars 51G                                ']},
{'ItemName': 'Snickers 50G                            ',
'RecItems': ['Twix 50G                                ',
 'Bounty 57G                              ',
 'Mars 51G                                ',
 'Mars 51G                                ',
 'Mars 51G                                ',
 'Bounty 57G                              ']},
{'ItemName': 'Cappy Mango 1.5L                        ',
'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
 'Cappy Orange 1.5L                       ',
 'Cappy Pear Kiwi & Cactus1.5L            ',
 'Cappy Grape 1.5L                        ']},
{'ItemName': 'Cappy Strawberry & Banana Drink 1.5L    ',
'RecItems': ['Cappy Grape 1.5L                        ',
 'Cappy Orange 1.5L                       ',
 'Cappy Mango 1.5L                        ',
 'Cappy Red Cherry  1.5L                  ',
 'Cappy Pear Kiwi & Cactus1.5L            ']},
{'ItemName': 'Cappy Lemon Mint Drink 1.5 L            ',
'RecItems': ['Cappy Orange 1.5L                       ',
 'Cappy Grape 1.5L                        ']},
{'ItemName': 'Fairy Lemon 16*650Ml                    ',
'RecItems': ['Fairy Lemon 9*1240 Ml                   ',
 'Fairy Original 9*1240 M                 ']},
{'ItemName': 'Fairy Lemon 9*1240 Ml                   ',
'RecItems': ['Fairy Lemon 16*650Ml                    ',
 'Fairy Orginal 16*650Ml                  ']},
{'ItemName': 'Seven Up 1L                             ',
'RecItems': ['Pepsi 1L                                ',
 'Mirinda 1L                              ',
 'Pepsi 1L                                ']},
{'ItemName': 'Produce 3.33 Nis                        ',
'RecItems': ['Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 8 Nis                           ',
 'Produce 5 Nis                           ',
 'Produce 7 Nis                           ']},
{'ItemName': 'Produce 5 Nis                           ',
'RecItems': ['Produce 8 Nis                           ',
 'Produce 9 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ']},
{'ItemName': 'Produce 10 Nis                          ',
'RecItems': ['Produce 9 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 7 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Produce 7 Nis                           ',
'RecItems': ['Produce 5 Nis                           ',
 'Produce 8 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ']},
{'ItemName': 'Fanta Orange 1.125L                     ',
'RecItems': ['Coca Cola 1.125L                        ',
 'Sprite 1.125L                           ',
 'Coca Cola 1.125L                        ']},
{'ItemName': 'Pringles Original 18*165Gr              ',
'RecItems': ['Pringles Sour Cream 18*165Gr            ',
 'Pringles Hot & Spicy 18*165Gr           ']},
{'ItemName': 'Produce 15 Nis                          ',
'RecItems': ['Produce 10 Nis                          ',
 'Produce 12 Nis                          ',
 'Produce 5 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 6 Nis                           ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Produce 4 Nis                           ',
'RecItems': ['Produce 3.33 Nis                        ',
 'Produce 6 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ']},
{'ItemName': 'Produce 12 Nis                          ',
'RecItems': ['Produce 9 Nis                           ',
 'Produce 15 Nis                          ',
 'Produce 8 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 10 Nis                          ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Bavaria Strawberry Can 330Ml            ',
'RecItems': ['Bavaria Apple Can 330Ml                 ',
 'Bavaria Peach Can 330Ml                 ',
 'Bavaria Pomegranate Can 330L            ']},
{'ItemName': 'Doritos W Pepper 45G                    ',
'RecItems': ['Doritos W/Grill 45G                     ',
 'Tabochips Lays 40G                      ']},
{'ItemName': 'Baby Wipes Purple                       ',
'RecItems': ['Baby Wipes Red                          ',
 'Baby Wipes Tango                        ',
 'Baby Wipes Tango                        ']},
{'ItemName': 'Sin. Al Quds Mort P.O.P                 ',
'RecItems': ['Homos Extra 250G                        ',
 'Mixed Salad 125G                        ']},
{'ItemName': 'Mixed Salad 125G                        ',
'RecItems': ['Sin. Al Quds Mort P.O.P                 ',
 'Al Junaidi Corn Salad 125G              ']},
{'ItemName': 'Coca Cola 1.125L                        ',
'RecItems': ['Fanta Orange 1.125L                     ',
 'Fanta Orange 1.125L                     ',
 'Sprite 1.125L                           ']},
{'ItemName': 'Produce Unit 12  Nis                    ',
'RecItems': ['Produce 3.33 Nis                        ',
 'Produce Unit 5 Nis                      ',
 'Produce 6 Nis                           ',
 'Produce 4 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ']},
{'ItemName': 'Sprite 1.125L                           ',
'RecItems': ['Fanta Orange 1.125L                     ',
 'Coca Cola 1.125L                        ',
 'Coca Cola 1.125L                        ']},
{'ItemName': 'Cappy Grape 1.5L                        ',
'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
 'Cappy Mango 1.5L                        ',
 'Cappy Lemon Mint Drink 1.5 L            ',
 'Cappy Red Cherry  1.5L                  ',
 'Cappy Orange 1.5L                       ',
 'Cappy Grapefruit 1.5 L                  ']},
{'ItemName': 'Cappy Red Cherry  1.5L                  ',
'RecItems': ['Cappy Grape 1.5L                        ',
 'Cappy Orange 1.5L                       ',
 'Cappy Strawberry & Banana Drink 1.5L    ',
 'Cappy Pear Kiwi & Cactus1.5L            ']},
{'ItemName': 'Produce Unit 5 Nis                      ',
'RecItems': ['Produce Unit 12  Nis                    ',
 'Produce 3.33 Nis                        ',
 'Produce 4 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Produce Unit 10 Nis                     ',
'RecItems': ['Produce 3.33 Nis                        ',
 'Produce Unit 5 Nis                      ',
 'Produce 4 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 5 Nis                           ']},
{'ItemName': 'Produce 13 Nis                          ',
'RecItems': ['Produce 15 Nis                          ',
 'Produce 10 Nis                          ',
 'Produce 12 Nis                          ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Produce 20 Nis                          ',
'RecItems': ['Produce 15 Nis                          ',
 'Produce 12 Nis                          ',
 'Produce 7 Nis                           ',
 'Produce 8 Nis                           ']},
{'ItemName': 'Osem Zaatar Snack Cracker 300G          ',
'RecItems': ['Crackerbegala 400G 8 Shape              ',
 'Crackerbegala Salty  Figners 375G       ']},
{'ItemName': 'Safi Sunflower Oil 5L                   ',
'RecItems': ['Addyafe Basmati Rice 5K                 ',
 'Abu Eta Noodles 200G                    ']},
{'ItemName': 'Salt Salit 1K 1*12                      ',
'RecItems': ['Al Sanabel Wheat Flour 1K               ',
 'Alraya Sugar 1K                         ',
 'Haifa Flour 1K                          ',
 'Rice Shukha Sunwhite 5K                 ']},
{'ItemName': 'Produce 8 Nis                           ',
'RecItems': ['Produce 9 Nis                           ',
 'Produce 9 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 5 Nis                           ']},
{'ItemName': 'Cappy Orange 1.5L                       ',
'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
 'Cappy Mango 1.5L                        ',
 'Cappy Lemon Mint Drink 1.5 L            ',
 'Cappy Red Cherry  1.5L                  ',
 'Cappy Grape 1.5L                        ',
 'Cappy Grapefruit 1.5 L                  ']},
{'ItemName': 'Roastery 40 Nis                         ',
'RecItems': ['Roastery 56                             ',
 'Roastery 32 Nis                         ',
 'Roastery 36 Nis                         ',
 'Roastery 60 Nis                         ']},
{'ItemName': 'Pringles Sour Cream 18*165Gr            ',
'RecItems': ['Pringles Original 18*165Gr              ',
 'Pringles Hot & Spicy 18*165Gr           ']},
{'ItemName': 'Alraya Sugar 1K                         ',
'RecItems': ['Salt Salit 1K 1*12                      ',
 'Haifa Flour 1K                          ']},
{'ItemName': 'Hand Soap Apple 500 Ml                  ',
'RecItems': ['Hand Soap Rose 500 Ml                   ',
 'Hand Soap Peach 500 Ml                  ',
 'Hand Soap Oat 500 Ml                    ']},
{'ItemName': 'Hand Soap Rose 500 Ml                   ',
'RecItems': ['Hand Soap Apple 500 Ml                  ',
 'Hand Soap Aolevera 500 Ml               ',
 'Hand Soap Peach 500 Ml                  ',
 'Hand Soap Oat 500 Ml                    ']},
{'ItemName': 'Pepsi 1L                                ',
'RecItems': ['Seven Up 1L                             ',
 'Mirinda 1L                              ',
 'Seven Up 1L                             ']},
{'ItemName': 'Bavaria Apple Can 330Ml                 ',
'RecItems': ['Bavaria Strawberry Can 330Ml            ',
 'Bavaria Peach Can 330Ml                 ',
 'Bavaria Pomegranate Can 330L            ']},
{'ItemName': 'Haifa Flour 1K                          ',
'RecItems': ['Alraya Sugar 1K                         ',
 'Salt Salit 1K 1*12                      ']},
{'ItemName': 'Produce 2.5 Nis                         ',
'RecItems': ['Produce Unit 5 Nis                      ',
 'Produce 3.33 Nis                        ',
 'Produce 6 Nis                           ',
 'Produce 4 Nis                           ',
 'Produce Unit 12  Nis                    ',
 'Produce Unit 10 Nis                     ']},
{'ItemName': 'Cappy Grapefruit 1.5 L                  ',
'RecItems': ['Cappy Orange 1.5L                       ',
 'Cappy Grape 1.5L                        ']},
{'ItemName': 'Cappy Pear Kiwi & Cactus1.5L            ',
'RecItems': ['Cappy Mango 1.5L                        ',
 'Cappy Orange 1.5L                       ',
 'Cappy Grape 1.5L                        ',
 'Cappy Red Cherry  1.5L                  ',
 'Cappy Strawberry & Banana Drink 1.5L    ']},
{'ItemName': 'Mars 51G                                ',
'RecItems': ['Snickers 50G                            ',
 'Bounty 57G                              ',
 'Twix 50G                                ',
 'Bounty 57G                              ',
 'Bounty 57G                              ',
 'Twix 50G                                ']},
{'ItemName': 'Produce 6 Nis                           ',
'RecItems': ['Produce 5 Nis                           ',
 'Produce 8 Nis                           ',
 'Produce 7 Nis                           ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ',
 'Produce 3.33 Nis                        ']},
{'ItemName': 'Seven Up 1.5L                           ',
'RecItems': ['Pepsi 1.5L                              ',
 'Mirinda 1.5L                            ']},
{'ItemName': 'Crackerbegala 400G 8 Shape              ',
'RecItems': ['Osem Zaatar Snack Cracker 300G          ',
 'Crackerbegala Salty  Figners 375G       ']},
{'ItemName': 'Baby Wipes Tango                        ',
'RecItems': ['Baby Wipes Purple                       ',
 'Baby Wipes Red                          ',
 'Baby Wipes Purple                       ']},
{'ItemName': 'Pringles Hot & Spicy 12*40Gr            ',
'RecItems': ['Pringles Sour Cream  12*40Gr            ',
 'Pringles Original 12*40Gr               ',
 'Pringles Original 12*40Gr               ']},
{'ItemName': 'Fairy Orginal 16*650Ml                  ',
'RecItems': ['Fairy Lemon 9*1240 Ml                   ',
 'Fairy Original 9*1240 M                 ']},
{'ItemName': 'Pringles Hot & Spicy 18*165Gr           ',
'RecItems': ['Pringles Original 18*165Gr              ',
 'Pringles Sour Cream 18*165Gr            ']},
{'ItemName': 'Bounty 57G                              ',
'RecItems': ['Twix 50G                                ',
 'Twix 50G                                ',
 'Mars 51G                                ',
 'Mars 51G                                ',
 'Mars 51G                                ',
 'Snickers 50G                            ']},
{'ItemName': 'Bavaria Peach Can 330Ml                 ',
'RecItems': ['Bavaria Strawberry Can 330Ml            ',
 'Bavaria Apple Can 330Ml                 ',
 'Bavaria Pomegranate Can 330L            ']},
{'ItemName': 'Pringles Original 12*40Gr               ',
'RecItems': ['Pringles Hot & Spicy 12*40Gr            ',
 'Pringles Hot & Spicy 12*40Gr            ',
 'Pringles Sour Cream  12*40Gr            ']},
{'ItemName': 'Pringles Sour Cream  12*40Gr            ',
'RecItems': ['Pringles Hot & Spicy 12*40Gr            ',
 'Pringles Hot & Spicy 12*40Gr            ',
 'Pringles Original 12*40Gr               ']},
{'ItemName': 'Hand Soap Peach 500 Ml                  ',
'RecItems': ['Hand Soap Apple 500 Ml                  ',
 'Hand Soap Rose 500 Ml                   ',
 'Hand Soap Oat 500 Ml                    ']},
{'ItemName': 'Bavaria Pomegranate Can 330L            ',
'RecItems': ['Bavaria Strawberry Can 330Ml            ',
 'Bavaria Peach Can 330Ml                 ',
 'Bavaria Apple Can 330Ml                 ']},
{'ItemName': 'Crackerbegala Salty  Figners 375G       ',
'RecItems': ['Crackerbegala 400G 8 Shape              ',
 'Osem Zaatar Snack Cracker 300G          ']},
{'ItemName': 'Fairy Original 9*1240 M                 ',
'RecItems': ['Fairy Orginal 16*650Ml                  ',
 'Fairy Lemon 16*650Ml                    ']},
{'ItemName': 'Mirinda 1L                              ',
'RecItems': ['Seven Up 1L                             ',
 'Pepsi 1L                                ',
 'Pepsi 1L                                ']},
{'ItemName': 'Hand Soap Oat 500 Ml                    ',
'RecItems': ['Hand Soap Peach 500 Ml                  ',
 'Hand Soap Apple 500 Ml                  ',
 'Hand Soap Rose 500 Ml                   ']}]
}
